[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 17.0


[colors.primary]
foreground = "#839496"
background = "#002b36"

[colors.cursor]
text = "#002b36"
cursor = "#839496"

[colors.selection]
text = "#93a1a1"
background = "#073642"

[colors.normal]
black = "#073642"
red = "#dc322f"
green = "#859900"
yellow = "#b58900"
blue = "#268bd2"
magenta = "#d33682"
cyan = "#2aa198"
white = "#eee8d5"

[colors.bright]
black = "#002b36"
red = "#cb4b16"
green = "#586e75"
yellow = "#657b83"
blue = "#839496"
magenta = "#6c71c4"
cyan = "#93a1a1"
white = "#fdf6e3"

# [colors.primary]
# background = "0x2D2A2E"
# foreground = "0xfff1f3"
#
# [colors.normal]
# black = "0x2c2525"
# red = "0xfd6883"
# green = "0xadda78"
# yellow = "0xf9cc6c"
# blue = "0xf38d70"
# magenta = "0xa8a9eb"
# cyan = "0x85dacc"
# white = "0xfff1f3"
#
# [colors.bright]
# black = "0x72696a"
# red = "0xfd6883"
# green = "0xadda78"
# yellow = "0xf9cc6c"
# blue = "0xf38d70"
# magenta = "0xa8a9eb"
# cyan = "0x85dacc"
# white = "0xfff1f3"
